# Generated by Django 6.1 on 2026-09-21 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='آدرس URL')),
                ('image', models.ImageField(upload_to='posts/%Y/%m/%d/', verbose_name='تصویر اصلی')),
                ('description', models.CharField(help_text='برای نمایش در کارت\u200cها و متا تگ\u200cها استفاده می\u200cشه', max_length=300, verbose_name='توضیح کوتاه')),
                ('content', models.TextField(verbose_name='متن کامل')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='دسته\u200cبندی')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='برند')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال تولید')),
                ('engine', models.CharField(blank=True, max_length=100, verbose_name='موتور')),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True, verbose_name='قدرت (اسب\u200cبخار)')),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'دنده\u200cای'), ('automatic', 'اتوماتیک')], max_length=20, verbose_name='گیربکس')),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'بنزینی'), ('diesel', 'دیزلی'), ('hybrid', 'هیبریدی'), ('electric', 'برقی')], max_length=20, verbose_name='نوع سوخت')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت (تومان)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
