# Generated by Django 6.1 on 2026-09-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='acceleration_0_100',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='زمان رسیدن از ۰ به ۱۰۰ کیلومتر بر ساعت، بر حسب ثانیه', max_digits=4, null=True, verbose_name='شتاب ۰ تا ۱۰۰ (ثانیه)'),
        ),
        migrations.AddField(
            model_name='post',
            name='torque',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='گشتاور (نیوتن\u200cمتر)'),
        ),
    ]
